### ISSUE TITLE
Update shrinkwrapped modules

### ISSUE THREAD

**Issue by joshuajabbour** [steve-jansen/json-proxy#23]
Morgan is not included in shrinkwrapped modules, so by default you get `Error: Cannot find module 'morgan'` when installing this package.

**Comment by steve-jansen** [comment]
Hi @joshuajabbour 

D'oh... failing to run `npm shrinkwrap` gets me again...  Thanks for reporting this!

**Comment by svincent** [comment]
In case anyone else runs into this, you can resolve the problem by `cd`ing to the directory that contains json-proxy and doing an `npm install morgan`.

I'm on a Mac and did a global install of json-proxy, so my directory was `/usr/local/lib/node_modules/json-proxy`.
